require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WordNotesController do

  # This should return the minimal set of attributes required to create a valid
  # WordNote. As you add validations to WordNote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "verse_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordNotesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all word_notes as @word_notes" do
      word_note = WordNote.create! valid_attributes
      get :index, {}, valid_session
      assigns(:word_notes).should eq([word_note])
    end
  end

  describe "GET show" do
    it "assigns the requested word_note as @word_note" do
      word_note = WordNote.create! valid_attributes
      get :show, {:id => word_note.to_param}, valid_session
      assigns(:word_note).should eq(word_note)
    end
  end

  describe "GET new" do
    it "assigns a new word_note as @word_note" do
      get :new, {}, valid_session
      assigns(:word_note).should be_a_new(WordNote)
    end
  end

  describe "GET edit" do
    it "assigns the requested word_note as @word_note" do
      word_note = WordNote.create! valid_attributes
      get :edit, {:id => word_note.to_param}, valid_session
      assigns(:word_note).should eq(word_note)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WordNote" do
        expect {
          post :create, {:word_note => valid_attributes}, valid_session
        }.to change(WordNote, :count).by(1)
      end

      it "assigns a newly created word_note as @word_note" do
        post :create, {:word_note => valid_attributes}, valid_session
        assigns(:word_note).should be_a(WordNote)
        assigns(:word_note).should be_persisted
      end

      it "redirects to the created word_note" do
        post :create, {:word_note => valid_attributes}, valid_session
        response.should redirect_to(WordNote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved word_note as @word_note" do
        # Trigger the behavior that occurs when invalid params are submitted
        WordNote.any_instance.stub(:save).and_return(false)
        post :create, {:word_note => { "verse_id" => "invalid value" }}, valid_session
        assigns(:word_note).should be_a_new(WordNote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WordNote.any_instance.stub(:save).and_return(false)
        post :create, {:word_note => { "verse_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested word_note" do
        word_note = WordNote.create! valid_attributes
        # Assuming there are no other word_notes in the database, this
        # specifies that the WordNote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WordNote.any_instance.should_receive(:update_attributes).with({ "verse_id" => "1" })
        put :update, {:id => word_note.to_param, :word_note => { "verse_id" => "1" }}, valid_session
      end

      it "assigns the requested word_note as @word_note" do
        word_note = WordNote.create! valid_attributes
        put :update, {:id => word_note.to_param, :word_note => valid_attributes}, valid_session
        assigns(:word_note).should eq(word_note)
      end

      it "redirects to the word_note" do
        word_note = WordNote.create! valid_attributes
        put :update, {:id => word_note.to_param, :word_note => valid_attributes}, valid_session
        response.should redirect_to(word_note)
      end
    end

    describe "with invalid params" do
      it "assigns the word_note as @word_note" do
        word_note = WordNote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WordNote.any_instance.stub(:save).and_return(false)
        put :update, {:id => word_note.to_param, :word_note => { "verse_id" => "invalid value" }}, valid_session
        assigns(:word_note).should eq(word_note)
      end

      it "re-renders the 'edit' template" do
        word_note = WordNote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WordNote.any_instance.stub(:save).and_return(false)
        put :update, {:id => word_note.to_param, :word_note => { "verse_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested word_note" do
      word_note = WordNote.create! valid_attributes
      expect {
        delete :destroy, {:id => word_note.to_param}, valid_session
      }.to change(WordNote, :count).by(-1)
    end

    it "redirects to the word_notes list" do
      word_note = WordNote.create! valid_attributes
      delete :destroy, {:id => word_note.to_param}, valid_session
      response.should redirect_to(word_notes_url)
    end
  end

end
